/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AgeRestriction = { 'teens' : null } |
  { 'kids' : null } |
  { 'none' : null } |
  { 'adultsOnly' : null };
export interface AttractionSpecificFields {
  'yearIntroduced' : [] | [bigint],
  'ageRestriction' : AgeRestriction,
  'hasGuidedTour' : boolean,
}
export interface AuditionLink {
  'url' : string,
  'title' : string,
  'auditionType' : AuditionType,
  'description' : string,
}
export interface AuditionSubmission {
  'submitter' : Principal,
  'formData' : { 'scareActor' : ScareActorAuditionForm } |
    { 'danceActor' : DanceAuditionForm },
  'auditionType' : AuditionType,
  'submissionTime' : Time,
}
export type AuditionType = { 'scareActor' : null } |
  { 'danceActor' : null };
export interface ContentItem {
  'id' : bigint,
  'useMainHauntSchedule' : boolean,
  'name' : string,
  'description' : string,
  'customType' : ContentType,
  'dates' : Array<EventDateRange>,
}
export type ContentType = { 'show' : ShowSpecificFields } |
  { 'event' : EventSpecificFields } |
  { 'scareZone' : ScareZoneSpecificFields } |
  { 'attraction' : AttractionSpecificFields };
export interface DanceAuditionForm {
  'age' : [] | [bigint],
  'performanceExperience' : string,
  'name' : string,
  'workingConditions' : string,
  'email' : string,
  'experience' : string,
  'availability' : string,
  'referredBy' : string,
  'whyDancing' : string,
  'favoriteDanceType' : string,
  'danceStyles' : string,
  'physicalLimitations' : string,
  'operationAgreeStatus' : string,
  'phone' : string,
  'scheduleConflicts' : string,
  'costumePreferences' : string,
  'previousWork' : string,
}
export interface Date { 'day' : bigint, 'month' : bigint, 'year' : bigint }
export interface EventDateRange { 'endDate' : Date, 'startDate' : Date }
export interface EventSpecificFields { 'eventType' : EventType }
export type EventType = { 'seasonal' : null } |
  { 'convention' : null } |
  { 'holiday' : null } |
  { 'specialEvent' : null } |
  { 'special' : null };
export type PerformanceType = { 'interactive' : null } |
  { 'theatrical' : null } |
  { 'stunt' : null } |
  { 'dance' : null } |
  { 'musical' : null };
export interface ScareActorAuditionForm {
  'age' : [] | [bigint],
  'specialSkills' : string,
  'conflictSchedule' : string,
  'name' : string,
  'email' : string,
  'experience' : string,
  'availability' : string,
  'referredBy' : string,
  'whyScaryRole' : string,
  'preferredScareType' : string,
  'preferenceOutfitType' : string,
  'preferedWorkingCondition' : string,
  'physicalLimitations' : string,
  'operationAgreeStatus' : string,
  'phone' : string,
  'favoriteCharacterType' : string,
  'previousWork' : string,
}
export type ScareLevel = { 'mild' : null } |
  { 'extreme' : null } |
  { 'moderate' : null };
export interface ScareZoneSpecificFields {
  'yearIntroduced' : [] | [bigint],
  'indoorOutdoor' : ZoneLocation,
  'scareLevel' : ScareLevel,
}
export interface ShowSpecificFields {
  'yearIntroduced' : [] | [bigint],
  'performanceType' : PerformanceType,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type ZoneLocation = { 'both' : null } |
  { 'indoor' : null } |
  { 'outdoor' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAuditionLink' : ActorMethod<[AuditionLink], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createContentItem' : ActorMethod<[ContentItem], bigint>,
  'deleteContentItem' : ActorMethod<[bigint], undefined>,
  'getAllAuditions' : ActorMethod<[], Array<AuditionSubmission>>,
  'getAllContentItems' : ActorMethod<[], Array<ContentItem>>,
  'getAttractions' : ActorMethod<[], Array<ContentItem>>,
  'getAuditionLinks' : ActorMethod<[], Array<AuditionLink>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContentItem' : ActorMethod<[bigint], [] | [ContentItem]>,
  'getEvents' : ActorMethod<[], Array<ContentItem>>,
  'getMainHauntSchedule' : ActorMethod<[], Array<EventDateRange>>,
  'getScareZones' : ActorMethod<[], Array<ContentItem>>,
  'getShows' : ActorMethod<[], Array<ContentItem>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'now' : ActorMethod<[], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedInitialContent' : ActorMethod<[], undefined>,
  'submitDanceAudition' : ActorMethod<[DanceAuditionForm], boolean>,
  'submitScareActorAudition' : ActorMethod<[ScareActorAuditionForm], boolean>,
  'updateContentItem' : ActorMethod<[bigint, ContentItem], undefined>,
  'updateMainHauntSchedule' : ActorMethod<[Array<EventDateRange>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];