/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AgeRestriction = { 'teens' : null } |
  { 'kids' : null } |
  { 'none' : null } |
  { 'adultsOnly' : null };
export interface AttractionSpecificFields {
  'yearIntroduced' : [] | [bigint],
  'ageRestriction' : AgeRestriction,
  'hasGuidedTour' : boolean,
}
export interface AuditionLink {
  'url' : string,
  'title' : string,
  'auditionType' : AuditionType,
  'description' : string,
}
export interface AuditionSubmission {
  'submitter' : Principal,
  'formData' : { 'scareActor' : ScareActorAuditionForm } |
    { 'costumeCharacter' : CostumeCharacterAuditionForm } |
    { 'usher' : UsherAuditionForm } |
    { 'danceActor' : DanceAuditionForm } |
    { 'hauntedHouseSupervisor' : HauntedHouseSupervisorAuditionForm },
  'auditionType' : AuditionType,
  'submissionTime' : Time,
}
export type AuditionType = { 'scareActor' : null } |
  { 'costumeCharacter' : null } |
  { 'usher' : null } |
  { 'danceActor' : null } |
  { 'hauntedHouseSupervisor' : null };
export type AvailabilityStatus = { 'inStock' : null } |
  { 'outOfStock' : null } |
  { 'limited' : null };
export interface Connection {
  'fromRoomId' : bigint,
  'tunnelSection' : string,
  'isOneWay' : boolean,
  'distance' : bigint,
  'toRoomId' : bigint,
}
export interface ContentItem {
  'id' : bigint,
  'useMainHauntSchedule' : boolean,
  'name' : string,
  'description' : string,
  'customType' : ContentType,
  'dates' : Array<EventDateRange>,
}
export type ContentType = { 'hauntedHouse' : HauntedHouseSpecificFields } |
  { 'show' : ShowSpecificFields } |
  { 'event' : EventSpecificFields } |
  { 'scareZone' : ScareZoneSpecificFields } |
  { 'attraction' : AttractionSpecificFields };
export interface CostumeCharacterAuditionForm {
  'age' : [] | [bigint],
  'name' : string,
  'musicalSkills' : string,
  'email' : string,
  'experience' : string,
  'referredBy' : string,
  'performancePreferences' : string,
  'vocalRange' : string,
  'physicalLimitations' : string,
  'operationAgreeStatus' : string,
  'phone' : string,
  'scheduleConflicts' : string,
  'costumePreferences' : string,
  'characterVoices' : string,
  'whyAudition' : string,
}
export interface DanceAuditionForm {
  'age' : [] | [bigint],
  'performanceExperience' : string,
  'name' : string,
  'workingConditions' : string,
  'email' : string,
  'experience' : string,
  'availability' : string,
  'referredBy' : string,
  'whyDancing' : string,
  'favoriteDanceType' : string,
  'danceStyles' : string,
  'physicalLimitations' : string,
  'operationAgreeStatus' : string,
  'phone' : string,
  'scheduleConflicts' : string,
  'costumePreferences' : string,
  'previousWork' : string,
}
export interface Date { 'day' : bigint, 'month' : bigint, 'year' : bigint }
export interface EventDateRange { 'endDate' : Date, 'startDate' : Date }
export interface EventSpecificFields { 'eventType' : EventType }
export type EventType = { 'seasonal' : null } |
  { 'convention' : null } |
  { 'holiday' : null } |
  { 'specialEvent' : null } |
  { 'special' : null };
export interface EventUnlockStatus {
  'hasSecretEntrance' : boolean,
  'hasFireworks' : boolean,
  'hasFlynAppearance' : boolean,
}
export interface FoodItem {
  'theme' : FoodTheme,
  'name' : string,
  'description' : string,
  'itemType' : FoodType,
  'price' : number,
  'allergens' : Array<string>,
  'specialNotes' : string,
}
export type FoodTheme = { 'paint' : null } |
  { 'death' : null };
export type FoodType = { 'dessert' : null } |
  { 'food' : null } |
  { 'drink' : null };
export interface HauntedHouseCharacter {
  'voiceType' : VoiceType,
  'name' : string,
  'description' : string,
  'scareType' : ScareType,
}
export interface HauntedHouseSpecificFields {
  'yearIntroduced' : [] | [bigint],
  'tagline' : string,
  'characters' : Array<HauntedHouseCharacter>,
  'sceneDescriptions' : Array<string>,
  'scareLevel' : ScareLevel,
}
export interface HauntedHouseSupervisorAuditionForm {
  'age' : bigint,
  'name' : string,
  'email' : string,
  'experience' : string,
  'availability' : string,
  'phone' : string,
  'leadershipExperience' : string,
}
export type LandStatus = { 'open' : null } |
  { 'underConstruction' : null } |
  { 'planned' : null };
export interface Location { 'x' : bigint, 'y' : bigint }
export interface MerchShop {
  'id' : bigint,
  'name' : string,
  'products' : Array<Product>,
  'location' : string,
}
export type PerformanceType = { 'interactive' : null } |
  { 'theatrical' : null } |
  { 'stunt' : null } |
  { 'dance' : null } |
  { 'musical' : null };
export interface Product {
  'name' : string,
  'description' : string,
  'availability' : AvailabilityStatus,
  'category' : ProductCategory,
  'price' : number,
}
export type ProductCategory = { 'posters' : null } |
  { 'skateboard' : null } |
  { 'clothes' : null } |
  { 'shoes' : null } |
  { 'autograph' : null };
export interface Room {
  'id' : bigint,
  'name' : string,
  'scareLevel' : ScareLevel,
  'location' : Location,
}
export interface RoomAssignment {
  'role' : string,
  'staffMember' : string,
  'roomId' : bigint,
  'shiftTime' : string,
}
export interface RoomSchedule {
  'timeSlots' : Array<TimeSlot>,
  'roomId' : bigint,
}
export interface ScareActorAuditionForm {
  'age' : [] | [bigint],
  'specialSkills' : string,
  'conflictSchedule' : string,
  'name' : string,
  'email' : string,
  'experience' : string,
  'availability' : string,
  'referredBy' : string,
  'whyScaryRole' : string,
  'preferredScareType' : string,
  'preferenceOutfitType' : string,
  'preferedWorkingCondition' : string,
  'physicalLimitations' : string,
  'operationAgreeStatus' : string,
  'phone' : string,
  'favoriteCharacterType' : string,
  'previousWork' : string,
}
export type ScareLevel = { 'mild' : null } |
  { 'extreme' : null } |
  { 'moderate' : null };
export type ScareType = { 'jumpScare' : null } |
  { 'ambient' : null } |
  { 'interactive' : null } |
  { 'psychological' : null } |
  { 'physical' : null };
export interface ScareZoneSpecificFields {
  'yearIntroduced' : [] | [bigint],
  'indoorOutdoor' : ZoneLocation,
  'scareLevel' : ScareLevel,
}
export interface ShowSpecificFields {
  'yearIntroduced' : [] | [bigint],
  'performanceType' : PerformanceType,
}
export interface StaffingCounts {
  'costumeCharacters' : bigint,
  'hauntedHouseSupervisors' : bigint,
  'zoneSupervisors' : bigint,
  'zoneActors' : bigint,
  'dancerSupervisors' : bigint,
  'princessPerformers' : bigint,
  'hauntedHouseActors' : bigint,
}
export interface ThemedFoodBooth {
  'id' : bigint,
  'deathMenu' : Array<FoodItem>,
  'name' : string,
  'description' : string,
  'location' : string,
  'paintMenu' : Array<FoodItem>,
}
export interface ThemedLand {
  'id' : bigint,
  'status' : LandStatus,
  'name' : string,
  'description' : string,
  'openingYear' : bigint,
  'sizeSqFt' : bigint,
  'futureShows' : Array<bigint>,
}
export type Time = bigint;
export interface TimeSlot { 'startTime' : string, 'endTime' : string }
export interface TunnelMap {
  'id' : bigint,
  'name' : string,
  'connections' : Array<Connection>,
  'rooms' : Array<Room>,
}
export interface TunnelSchedule {
  'id' : bigint,
  'roomAssignments' : Array<RoomAssignment>,
  'date' : string,
  'shift' : string,
  'specialEvent' : [] | [string],
  'roomSchedules' : Array<RoomSchedule>,
}
export interface UpcomingEvent {
  'day' : bigint,
  'month' : bigint,
  'title' : string,
  'year' : bigint,
  'description' : string,
  'featureTransactionType' : string,
  'isUnlocked' : boolean,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UsherAuditionForm {
  'age' : bigint,
  'name' : string,
  'email' : string,
  'experience' : string,
  'availability' : string,
  'phone' : string,
}
export type VoiceType = { 'lowPitch' : null } |
  { 'creepy' : null } |
  { 'playful' : null } |
  { 'silent' : null } |
  { 'highPitch' : null };
export type ZoneLocation = { 'both' : null } |
  { 'indoor' : null } |
  { 'outdoor' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAuditionLink' : ActorMethod<[AuditionLink], undefined>,
  'addFoodBooth' : ActorMethod<[ThemedFoodBooth], undefined>,
  'addMerchShop' : ActorMethod<[MerchShop], undefined>,
  'addRoomAssignments' : ActorMethod<[Array<RoomAssignment>], undefined>,
  'addThemedLand' : ActorMethod<[ThemedLand], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearAuditionLinks' : ActorMethod<[], undefined>,
  'createContentItem' : ActorMethod<[ContentItem], bigint>,
  'createTunnelMap' : ActorMethod<
    [string, Array<Room>, Array<Connection>],
    bigint
  >,
  'createTunnelSchedule' : ActorMethod<
    [string, string, [] | [string], Array<RoomAssignment>, Array<RoomSchedule>],
    bigint
  >,
  'deleteContentItem' : ActorMethod<[bigint], undefined>,
  'deleteFoodBooth' : ActorMethod<[bigint], undefined>,
  'deleteMerchShop' : ActorMethod<[bigint], undefined>,
  'deleteThemedLand' : ActorMethod<[bigint], undefined>,
  'deleteTunnelMap' : ActorMethod<[bigint], undefined>,
  'deleteTunnelSchedule' : ActorMethod<[bigint], undefined>,
  'getAllAuditions' : ActorMethod<[], Array<AuditionSubmission>>,
  'getAllContentItems' : ActorMethod<[], Array<ContentItem>>,
  'getAllFoodBooths' : ActorMethod<[], Array<ThemedFoodBooth>>,
  'getAllMerchShops' : ActorMethod<[], Array<MerchShop>>,
  'getAllThemedLands' : ActorMethod<[], Array<ThemedLand>>,
  'getAllTunnelMaps' : ActorMethod<[], Array<TunnelMap>>,
  'getAllTunnelSchedules' : ActorMethod<[], Array<TunnelSchedule>>,
  'getAttractions' : ActorMethod<[], Array<ContentItem>>,
  'getAuditionLinks' : ActorMethod<[], Array<AuditionLink>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContentItem' : ActorMethod<[bigint], [] | [ContentItem]>,
  'getEmployeeUpcomingEvents' : ActorMethod<[Date], Array<UpcomingEvent>>,
  'getEventUnlockStatus' : ActorMethod<[], EventUnlockStatus>,
  'getEvents' : ActorMethod<[], Array<ContentItem>>,
  'getFoodBooth' : ActorMethod<[bigint], [] | [ThemedFoodBooth]>,
  'getHauntedHouses' : ActorMethod<[], Array<ContentItem>>,
  'getMainHauntSchedule' : ActorMethod<[], Array<EventDateRange>>,
  'getMerchShop' : ActorMethod<[bigint], [] | [MerchShop]>,
  'getRoomAssignments' : ActorMethod<[], Array<Array<RoomAssignment>>>,
  'getScareZones' : ActorMethod<[], Array<ContentItem>>,
  'getShows' : ActorMethod<[], Array<ContentItem>>,
  'getStaffingCounts' : ActorMethod<[], StaffingCounts>,
  'getThemedLand' : ActorMethod<[bigint], [] | [ThemedLand]>,
  'getTunnelMap' : ActorMethod<[bigint], [] | [TunnelMap]>,
  'getTunnelSchedule' : ActorMethod<[bigint], [] | [TunnelSchedule]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'now' : ActorMethod<[], bigint>,
  'removeAuditionLink' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedInitialContent' : ActorMethod<[], undefined>,
  'submitCostumeCharacterAudition' : ActorMethod<
    [CostumeCharacterAuditionForm],
    boolean
  >,
  'submitDanceAudition' : ActorMethod<[DanceAuditionForm], boolean>,
  'submitHauntedHouseSupervisorAudition' : ActorMethod<
    [HauntedHouseSupervisorAuditionForm],
    boolean
  >,
  'submitScareActorAudition' : ActorMethod<[ScareActorAuditionForm], boolean>,
  'submitUsherAudition' : ActorMethod<[UsherAuditionForm], boolean>,
  'updateAuditionLink' : ActorMethod<[bigint, AuditionLink], undefined>,
  'updateContentItem' : ActorMethod<[bigint, ContentItem], undefined>,
  'updateFoodBooth' : ActorMethod<[bigint, ThemedFoodBooth], undefined>,
  'updateMainHauntSchedule' : ActorMethod<[Array<EventDateRange>], undefined>,
  'updateMerchShop' : ActorMethod<[bigint, MerchShop], undefined>,
  'updateThemedLand' : ActorMethod<[bigint, ThemedLand], undefined>,
  'updateTunnelMap' : ActorMethod<[bigint, TunnelMap], undefined>,
  'updateTunnelSchedule' : ActorMethod<[bigint, TunnelSchedule], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];