export const generatedImages = {
  hauntedHouses: {
    'Terror Hell hole': '/assets/generated/house-terror-hell-hole.dim_1400x900.jpg',
    'Clown town': '/assets/generated/house-clown-town-haunted-house.dim_1400x900.jpg',
    'Asylum hell': '/assets/generated/house-asylum-hell.dim_1400x900.jpg',
    'Schoolhouse break and blackout': '/assets/generated/house-schoolhouse-break.dim_1400x900.jpg',
    'Toys Come to Play': '/assets/generated/house-toys-come-to-play.dim_1400x900.jpg',
    'Diner Hell': '/assets/generated/house-diner-hell-logo.dim_1400x900.jpg',
    'Toxic Trails Science': '/assets/generated/house-toxic-trails-science-logo.dim_1400x900.jpg',
    'Open Ice Tomb': '/assets/generated/house-open-ice-tomb.dim_1400x900.jpg',
    'Wax Works': '/assets/generated/house-wax-works.dim_1400x900.jpg',
  },
  scareZones: {
    'Carnival Bros Circus': '/assets/generated/zone-carnival-bros-circus.dim_1400x900.jpg',
    'Zombie Hell': '/assets/generated/zone-undead-dance-party.dim_1400x900.jpg',
    'Screamtown Chaos': '/assets/generated/zone-playtimes-over.dim_1400x900.jpg',
    'Grave danger dace': '/assets/generated/zone-laser-hell.dim_1400x900.jpg',
    'Steampunk Hell': '/assets/generated/zone-steampunk-hell.dim_1400x900.jpg',
    'Santa\'s Hell': '/assets/generated/zone-santas-hell.dim_1400x900.jpg',
    'Chainsaw Cold': '/assets/generated/zone-chainsaw-cold.dim_1400x900.jpg',
  },
  foodBooths: {
    'Clown town Chicken': '/assets/generated/booth-clown-town-chicken.dim_1400x900.jpg',
    'Hell hole bbq': '/assets/generated/booth-hell-hole-bbq.dim_1400x900.jpg',
    'Schoolhouse Fish': '/assets/generated/booth-schoolhouse-fish.dim_1400x900.jpg',
    'Asylum Seekers': '/assets/generated/booth-asylum-seekers-chain-pizza.dim_1400x900.jpg',
    "Felix's Yum": '/assets/generated/booth-felixs-yum.dim_1400x900.jpg',
    'Scary bears spicy eyes': '/assets/generated/booth-scary-bears-spicy-eyes.dim_1400x900.jpg',
    'Terror bite': '/assets/generated/booth-terror-bite.dim_1400x900.jpg',
    'chaos  carnival': '/assets/generated/booth-chaos-carnival.dim_1400x900.jpg',
    'Slider Doom': '/assets/generated/booth-slider-doom.dim_1400x900.jpg',
    'Sharks Hell': '/assets/generated/booth-sharks-hell.dim_1400x900.jpg',
    'Steampunk Eats': '/assets/generated/booth-steampunk-eats.dim_1400x900.jpg',
    'Gingerdead Bakes': '/assets/generated/booth-gingerdead-bakes.dim_1400x900.jpg',
    'Hellfire Hot Cocoa': '/assets/generated/booth-hellfire-hot-cocoa.dim_1400x900.jpg',
    'Wrath of Wrapping': '/assets/generated/booth-wrath-of-wrapping.dim_1400x900.jpg',
    'Eggnog Exorcism': '/assets/generated/booth-eggnog-exorcism.dim_1400x900.jpg',
    'Candy Cane Carnage': '/assets/generated/booth-candy-cane-carnage.dim_1400x900.jpg',
    'Ornament Ossuary': '/assets/generated/booth-ornament-ossuary.dim_1400x900.jpg',
  },
  auditions: {
    'The Scream Team Auditions': '/assets/generated/auditions-scream-team.dim_1400x900.jpg',
    'Show Host Auditions': '/assets/generated/auditions-show-host-auditions.dim_1400x900.jpg',
    'Costume Character Auditions': '/assets/generated/costume-character-audition-cast-group.dim_1600x900.jpg',
  },
  shows: {
    'Lost spirits': '/assets/generated/show-lost-spirits.dim_1400x900.jpg',
    'Dead mans revenge': '/assets/generated/show-dead-mans-revenge.dim_1400x900.jpg',
    'Fire Remix': '/assets/generated/show-fire-remix.dim_1400x900.jpg',
    'Camp Riley': '/assets/generated/show-camp-riley.dim_1400x900.jpg',
  },
  events: {
    'Chaos Purge': '/assets/generated/event-chaos-purge.dim_1400x900.jpg',
    'Frosted Haunt': '/assets/generated/event-frosted-haunt.dim_1400x900.jpg',
    'Viva Nova': [
      '/assets/generated/event-viva-nova-1.dim_1400x900.jpg',
      '/assets/generated/event-viva-nova-2.dim_1400x900.jpg',
      '/assets/generated/event-viva-nova-3.dim_1400x900.jpg',
    ],
    'DMV Harbor Nights': [
      '/assets/generated/event-dmv-harbor-nights-1.dim_1400x900.jpg',
      '/assets/generated/event-dmv-harbor-nights-2.dim_1400x900.jpg',
      '/assets/generated/event-dmv-harbor-nights-3.dim_1400x900.jpg',
    ],
    'TCEA Horror Nights': [
      '/assets/generated/event-tcea-horror-nights-1.dim_1400x900.jpg',
      '/assets/generated/event-tcea-horror-nights-2.dim_1400x900.jpg',
      '/assets/generated/event-tcea-horror-nights-3.dim_1400x900.jpg',
    ],
  },
  upcomingEvents: {
    'Chaos Purge': '/assets/generated/event-chaos-purge.dim_1400x900.jpg',
    'Frosted Haunt': '/assets/generated/event-frosted-haunt.dim_1400x900.jpg',
    'Viva Nova': [
      '/assets/generated/event-viva-nova-1.dim_1400x900.jpg',
      '/assets/generated/event-viva-nova-2.dim_1400x900.jpg',
      '/assets/generated/event-viva-nova-3.dim_1400x900.jpg',
    ],
    'DMV Harbor Nights': [
      '/assets/generated/event-dmv-harbor-nights-1.dim_1400x900.jpg',
      '/assets/generated/event-dmv-harbor-nights-2.dim_1400x900.jpg',
      '/assets/generated/event-dmv-harbor-nights-3.dim_1400x900.jpg',
    ],
    'TCEA Horror Nights': [
      '/assets/generated/event-tcea-horror-nights-1.dim_1400x900.jpg',
      '/assets/generated/event-tcea-horror-nights-2.dim_1400x900.jpg',
      '/assets/generated/event-tcea-horror-nights-3.dim_1400x900.jpg',
    ],
  },
  sneakPeeks: {
    schoolhouse: '/assets/generated/schoolhouse-sneak-peek-elevation.dim_1600x900.jpg',
    clownTown: '/assets/generated/clown-town-interior-elevation-v2.dim_1600x900.jpg',
    hellHole: '/assets/generated/house-terror-hell-hole.dim_1400x900.jpg',
    vickysSaw: '/assets/generated/vickys-saw-scenic-elevation.dim_1600x900.jpg',
    toysComeToPlay: '/assets/generated/house-toys-come-to-play.dim_1400x900.jpg',
  },
  misc: {
    procession: '/assets/generated/procession-main-street-plaza.dim_1600x900.jpg',
    felixMerchBooth: '/assets/generated/felix-merch-booth-sneak-peek.dim_1600x900.jpg',
  },
  merch: {
    'Felix Merch Booth': '/assets/generated/felix-merch-booth-sneak-peek.dim_1600x900.jpg',
  },
  attraction: {
    exterior: '/assets/generated/attraction-exterior.dim_1600x900.jpg',
  },
};
